<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <RestoreLockedMode>false</RestoreLockedMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MonadicTypes.Async\MonadicTypes.Async.csproj" />
    <ProjectReference Include="..\..\src\MonadicTypes.AspNetCore\MonadicTypes.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\MonadicTypes.Diagnostics\MonadicTypes.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\MonadicTypes.Effects\MonadicTypes.Effects.csproj" />
    <ProjectReference Include="..\..\src\MonadicTypes.Generators\MonadicTypes.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
