<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <RestoreLockedMode>false</RestoreLockedMode>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MonadicTypes.Collections\MonadicTypes.Collections.csproj" />
    <ProjectReference Include="..\..\src\MonadicTypes.Linq\MonadicTypes.Linq.csproj" />
  </ItemGroup>
</Project>
